import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Layout } from '@/components/Layout'
import profilePic from '../../public/images/profile/developer-pic-1.png';
import { AnimatedText } from '@/components/AnimatedText'
import Link from 'next/link'
import { CircularText, LinkArrow } from '@/components/Icons'
import { HireMe } from '@/components/HireMe'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex item-center text-dark w-full">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image src={profilePic} alt="Astronomer" className="h-auto w-full"/>
            </div>
            <div class="w-1/2 flex flex-col items-center self-center">
              <h1></h1>
              <AnimatedText text = "Astrophotography Adventures: Capturing the Wonders of the Cosmos." className="!text-5xl text-left" />
              <p className='my-4 text-base font-medium'>Welcome to my astrophotography portfolio, where I capture the ethereal beauty of celestial objects. Join me on a visual journey through the mysteries of space, revealing the wonders that await us in the night sky. Let unveil the secrets of the universe, one captivating photograph at a time.</p>
              <div className = "flex items-center self-start mt-2">
                <Link href="/dummy.pdf" target={"_blank"} className="flex items-center bg-dark text-light p-1.5 px-5 rounded-lg text-lg font-semibold border-2 border-solid border-transparent hover:border-dark hover:bg-light hover:text-dark mr-3" download = {true}>Resume <LinkArrow className={"w-6 ml-1"}/>
                </Link>
                <Link href="mailto:abc@gmail.com" target="{_blank}" className="flex items-center bg-light text-dark p-1.5 px-5 rounded-lg text-lg font-semibold border-2 border-solid border-transparent hover:border-dark hover:bg-dark hover:text-light">Contact</Link>
                <HireMe />
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
